[firebase]
type = "service_account"
project_id = "app2-2-e705a"
private_key_id = "816e31c41f07524022015e9317d06341715a8283"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGHtpNScPI8RPr
uJbDFXRlOsWoHm+HBqhwX3YOtfYcXI27cIytBlWTdDlRMF/qxOMheJTzgB8staAl
8qhfixul9iQ/mZB3ZfOuHQZmaMI38NbUiJGFG47iisDWyKt9qVeEQiqPg7tEmz5x
IlyKdjM7dkzCP8o9uxtjjhgMnLyYo5IrGCUmsNepkslYg8Qo6zNMjOCMOVNmDBPO
m7Q0M6cJwmvNc9y4ga6AbpCi0tidP5GzXaGHkWH/YCjVUBTz39ET/NnL9vGIxo2f
aQ/yQOQzoD5/dnbJpaVQzZVTF3M751cfPamkEmBERt3AwWN5bO9HXlCUysa0Xy/u
COa+sQ4lAgMBAAECggEAAp4xwEezQJp+6uR7iYRlD1lhd0E/tAcQfrukMbmR0Pog
HVP1Z+vngZVNlJcRDWcgoTaYsUcGIm8b+KRmOSz7ZowEGpsK36kHOUvE4+GKf3a9
P/21/o5IqxGuTqhEK9rq/yJosZDKDrQGdTRBCMtbDfQYO5DgOUSZrg0YoEIJ8/Jf
ay5FlUZ++ix1IeJ7F4svU34yS/Zh9hGsvUkaVeqT/phVgqpwkftoSz5gytS3UBMy
LFhMLALFWTyfyJevOzxvBQL7dkA74+Pzon+eyKvjKO7sw+lxkHo93SaYtsU5xfI7
Vs4UsAgAUWrcBnMc/pXIAtqjAejkKhf5BszOukmymQKBgQDwW+9r0X/YK6Q4j7zb
EbgqJoWPaYw79q1GN4HctNzmLhQd11lrDXqBSrl+VT8+y9bDUDqsNOQNOuDnPPyp
Ur/Qsx3TeX7lSqQo+8wAE/RnXEwaTtuKzCxfr2+dTlpb7kJ4sUsUzksKs9MK+PaE
nFXQ0HLdDTyA4k6+u7gINOzxbwKBgQDTA0c95pvvVLaau+JoyarMDVaaZndQDxvB
e1wrvb0PvD+251ZiK+vmEgkDwZoP1DcR7ClPGQy1IoKAfw97Uf//836D42iiYHja
KNvxoTRMHkAg/IQE2Eiw0k10XNlPH4btfqxgLtmPFbiR8zTdLdvSAkHPmVKJhSof
+GzL4upHqwKBgBLWIZ1BfdNjGCuWmCZS7SvgePcUPnk0i7/E+dhiFC21zr3H8qoB
FGitgnv0ElDJiLslvnNgcb7Xrmhwzxw17/JbFytLijZN8y+DDCm1ZqHzCcPGCk6G
UbPt+8FIMqyhr3Pl8QxgXmEoVpG1kRwzZEZJD7djIiq3kZRBAdsiyq7hAoGATk68
JIOtQL8eWQP6vMqCYOFeT0RRaNuCgGYISY9LV0iUGIt3ak1EaQguYj95rgAiQ7tx
hRIVvi7FYWxF0Y0XxOOXAtjk3sWQc92P6fbaEplzUQqE78tYBo61AcbnOk7H4uEM
lVEtmcUEzt0DtEUte50s0R7kG3bYsC6gKXXXXasCgYEArxrs0MHdwTBE5i3Waf1a
PEDEAizmzJ8qsyQ+g/UFdTOXusVnq3IND6ULj13CfIHSkQa9ILuBZedYJFMU11ia
j3MK3tip7h6GTYdwGGHfl7daRlnnLyT4YDO9IXVsICCOiufn6YIYAq36Vlwl2KWY
4xgRaBKd6+3Y6N4bT+j++KA=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@app2-2-e705a.iam.gserviceaccount.com"
client_id = "113319025028580822725"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40app2-2-e705a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"